FROM arm64v8/ubuntu

WORKDIR /scripts

RUN apt-get update && \
    apt-get install python3.6 -y 
    # Install ffmpeg


# Copy scripts

# Run scripts

# Script Ideas:
    # Slow down and add reverb
    # Add video to an audio stream????
    # post to youtube with api:
        # title, thumbnail, description

